### ISSUE TITLE
Train data

### ISSUE THREAD

**Issue by LeonCurry** [konstantg/dem-fill#2]
@konstantg  I have check the code. I am sorry to bother you.  I want to know the specific information of the train data, such as the format of the train data, the bits of images, and so on. Thanks for your patience.

**Comment by konstantg** [comment]
@LeonCurry Please have a look at the `data` folder of the project for some examples. The train data are `.tif` files and the masks are `.png`.

**Comment by LeonCurry** [comment]
Dear @konstantg ,
I have checked your neuralgym files. I have a question, can you explain these lines([here](https://github.com/konstantg/neuralgym/blob/f895fef2e0a1bfa3c636daaaad44f15a710b21a2/neuralgym/data/data_from_fnames.py#L199))

**Comment by LeonCurry** [comment]
Dear @konstantg ,
I have read your neuralgym files carefully. I have a question, can you explain these lines([here](https://github.com/konstantg/neuralgym/blob/f895fef2e0a1bfa3c636daaaad44f15a710b21a2/neuralgym/data/data_from_fnames.py#L199) and [here](https://github.com/konstantg/neuralgym/blob/f895fef2e0a1bfa3c636daaaad44f15a710b21a2/neuralgym/data/data_from_fnames.py#L200)).
When I modified the code according to your two lines, I can run train.py. But there will be an error when I use this `img = tf.reshape(img,[img.shape[0],img.shape[1],1]`. Can you explain this question?  Looking forward to your reply.

**Comment by LeonCurry** [comment]
img = tf.reshape(img,[img.shape[0],img.shape[1],1])

**Comment by tangeroo** [comment]
@LeonCurry  no such file or directory：‘data/train_shuffled.flist’.Have you ever met this problem?How did you fix it?

**Comment by LeonCurry** [comment]
You can see [here](https://github.com/JiahuiYu/generative_inpainting/issues/15).  @tangeroo

**Comment by tangeroo** [comment]
@LeonCurry  thank you very much

**Comment by LeonCurry** [comment]
Can I ask you a question? Does your training data just have `oslo.tif,` `bergen.tif` and` trondheim.tif`?  And then random crop from this three tif images? @konstantg

**Comment by tangeroo** [comment]
@LeonCurry I have not trained yet.But I think the data you mentioned above is not enough,which is just some examples that the author gives.Do you mind I add your QQ?

**Comment by LeonCurry** [comment]
83292414 @tangeroo

**Comment by konstantg** [comment]
@LeonCurry Yes, that is right. It was my workaround for this project. If you wish to work with a set of images you can look at the original image inpanting repository.

**Comment by LP429** [comment]
Hi, @LeonCurry! How is your work going? I'm also working on this but I don't know how to change data_from_fnames.py and can't run train.py. Can you give me some advice? Thank you very much!
