### ISSUE TITLE
Negative Loss

### ISSUE THREAD

**Issue by htn274** [konstantg/dem-fill#6]
I have been testing your model on SRTM (resolution 30m) on Mekong basin region.
When I run the model, I got below error: 
![Screenshot from 2020-06-04 11-08-39](https://user-images.githubusercontent.com/26211514/83714116-12237a00-a654-11ea-942c-d071f596af28.png)
Then, I found that it is because of incompatible shape of offset_flow:

https://github.com/konstantg/dem-fill/blob/10dcaf08c444cc812ef2380fb0d6e9840a1e2603/inpaint_model.py#L193

I fixed it by changing **flow_to_image_tf** function and run the model successfully.
![Screenshot from 2020-06-04 11-09-04](https://user-images.githubusercontent.com/26211514/83714176-4303af00-a654-11ea-999e-30a291e96842.png)

While training, I got the negative loss: 
![Screenshot from 2020-06-04 11-07-46](https://user-images.githubusercontent.com/26211514/83714452-008ea200-a655-11ea-9449-8e219cb48275.png)

I'd like to ask you that is the negative loss normal and is my works corrected?
Your answer will help me a lot! 
Thank you!

**Comment by konstantg** [comment]
@htn274 Hi and thank you for your interest and for sharing the fix to your issue.

Negative loss is indeed normal. Allow it to train until convergence.
