### ISSUE TITLE
How to modify data_from_fnames.py?

### ISSUE THREAD

**Issue by LP429** [konstantg/dem-fill#7]
@konstantg Hi,konstantg.Great results and thank you for  sharing.
When I tried to run the code, there was a problem:
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 3. Shapes are [1] and [3]. for 'concat_7' (op: 'ConcatV2') with input shapes: [32,256,256,1], [32,256,256,1], [32,256,256,1], [32,256,256,3], [] and with computed input tensors: input[4] = <2>.
I see that your work needs to modify data_from_fnames.py. So how should I modify this file?
Thank you!

**Comment by konstantg** [comment]
@LP429 Hi and thank you for your interest in our work.

Notice that you need to have our version of [neuralgym](https://github.com/konstantg/neuralgym) to run our code, which is different from the [original version](https://github.com/JiahuiYu/neuralgym). We minimally modified `data_from_fnames.py` among others to serve our needs.

 In our case, `data_from_fnames.py` loads large DEMs of Norway in the form of `.tif` files, and then generates training batches by randomly cropping these DEMs. This is much more convenient and storage-friendly from the usual approach where each training sample would be a separate file.

If you want to experiment or alter the code, you should modify the above accordingly.

**Comment by LP429** [comment]
@konstantg  Thanks for your quick reply and advice！I will read these codes carefully~

**Comment by LP429** [comment]
@konstantg Thanks for your quick reply and advice！I will read these codes carefully~

**Comment by SvSz** [comment]
having exactly the same issue. not even using my own data but when trying the land.tif data set (only the 3 .tif images in total)
I use python 3.6 and tensorflow 1.15 on Ubuntu 22.04

**Comment by SvSz** [comment]
@LP429 Did you have any success finding the issue and solve it?

**Comment by ypc2002** [comment]
> 

Did you solve the problem?Pls help me!

**Comment by ypc2002** [comment]
@SvSz

**Comment by SvSz** [comment]
maybe i can have a look and share my code these days. but i had other errors i couldnt solve afterwards... i think this error has something to do with the wrong folder managment.

**Comment by ypc2002** [comment]
@SvSz I used three channels for all the images, and then modified the code a bit. The model can run through, but the prediction cannot be made because the variables are different. I can't understand why. So, I am now debugging with the original single channel DEM, and I encountered this initial problem. Thank you so much for your reply!hope we can work it out.

**Comment by ypc2002** [comment]
@SvSz I have solved the problem, you need to change the 3 in img.set_shape(flow.get_shape().as_list()[0:-1]+[3]) to 1.（inpaint_ops 463）
